import { useNavigate } from 'react-router-dom';
import './App.css';
import { Routes } from 'routes';
import { Amplify } from 'aws-amplify';
import { getCurrentUser } from 'aws-amplify/auth';
import { Hub } from 'aws-amplify/utils';
import '@aws-amplify/ui-react/styles.css';
import { useEffect } from 'react';
import { useAuth } from 'shared/hooks';
import { Toaster } from 'react-hot-toast';

// Amplify Gen 2: configure from amplify_outputs.json
// This file is auto-generated by `npx ampx sandbox` or during deployment
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import outputs from '../amplify_outputs.json';

Amplify.configure(outputs);

// Register custom REST API Gateway so aws-amplify/api get/post can use it
const existingConfig = Amplify.getConfig();
Amplify.configure({
  ...existingConfig,
  API: {
    ...existingConfig.API,
    REST: {
      AirRestApi: {
        endpoint: outputs.custom.apiUrl,
        region: outputs.auth.aws_region,
      },
    },
  },
});

function App() {
  const navigate = useNavigate();
  const { setUser, error, setError, setIsLoading, clearUser, isAuthenticated, checkSessionRevoked } = useAuth();

  useEffect(() => {
    Hub.listen('auth', (data) => {
      switch (data.payload.event) {
        case 'signedOut':
          clearUser();
          navigate('/');
          break;
      }
    });
  }, [navigate]);

  useEffect(() => {
    const getAuthenticatedUser = async () => {
      try {
        const user = await getCurrentUser();
        if (user) {
          setUser(user);
        } else {
          throw new Error('No user');
        }
      } catch (_err) {
        setIsLoading(false);
      }
    };

    getAuthenticatedUser();
  }, [setUser, setIsLoading]);

  useEffect(() => {
    if (!isAuthenticated) return;
    const interval = setInterval(checkSessionRevoked, 30000);
    return () => clearInterval(interval);
  }, [isAuthenticated, checkSessionRevoked]);

  useEffect(() => {
    if (error === '') return;
    let timeout: ReturnType<typeof setTimeout> | undefined;
    try {
      timeout = setTimeout(() => {
        setError('');
      }, 7000);
    } catch (_err) {
      /* ignore */
    }
    return () => clearTimeout(timeout);
  }, [error, setError]);

  return (
    <>
      <Toaster position="top-right" />
      <Routes />
    </>
  );
}

export default App;
